### ISSUE TITLE
Crash if no .editorconfig found

### ISSUE THREAD

**Issue by Bartheleway** [evanshortiss/lintspaces-cli#33]
It seems that lintspaces-cli default to expecting a .editorconfig file to be present which kind of prevent me from using the command line arguments.

Could you make this optional as lintspaces is not tighted with editorconfig?

**Comment by evanshortiss** [comment]
This issue is caused by a change in 0.8.0 that I should've given better consideration. Can you try out the current version I just pushed and let me know if it works for you?

```bash
# Run this, and pass your options to run lintspaces
npx evanshortiss/lintspaces-cli#master
```

**Comment by Bartheleway** [comment]
Maybe the base package also have an issue, here is the stack trace:
```
Error: The editorconfig file ".editorconfig" wasn't found.
    at Validator._fail ([globalStorage]\node_modules\lintspaces-cli\node_modules\lintspaces\src\Validator.js:701:9)
    at Validator._loadSettingsEditorconfig ([globalStorage]\node_modules\lintspaces-cli\node_modules\lintspaces\src\Validator.js:237:10)
    at Validator._loadSettings ([globalStorage]\node_modules\lintspaces-cli\node_modules\lintspaces\src\Validator.js:179:8)
    at Validator.validate ([globalStorage]\npm\node_modules\lintspaces-cli\node_modules\lintspaces\src\Validator.js:83:9)
    at module.exports ([globalStorage]\node_modules\lintspaces-cli\index.js:165:15)
    at Object.<anonymous> ([globalStorage]\node_modules\lintspaces-cli\bin\lintspaces-cli.js:3:20)
```

Strangely, it works correctly when I do `npx evanshortiss/lintspaces-cli#master .` or `lintspaces .` but fails with the stack trace given when doing `npx evanshortiss/lintspaces-cli#master ./**` or `lintspaces ./**`

**Comment by Bartheleway** [comment]
I confirm this works perfectly 👍I had to uninstall lintspaces-cli before running the npx command to be able to test.

Also, I know that lintspaces is having a new version really soon, it could be great to wait for this before releasing your version 😉

**Comment by evanshortiss** [comment]
Fantastic. Have you got a link to where the new lintspaces version is being tracked?

**Comment by Bartheleway** [comment]
Not really, I just got the information on an opened issue of the package as we manage to agree on a fix :)

As of yesterday
> This is merged to main and I will make a release today.

So it is a question of days I think and also good thing is that it will fix some issue when using a .editorconfig file.

**Comment by evanshortiss** [comment]
@Bartheleway 1.0.0 is live!
